i-am-bee/beeai-framework

.github/PULL_REQUEST_TEMPLATE.md

Closes: #12
This is a first draft of a PR template for the project intended for review/discussion and potential modification prior to being merged.  The intention of the template is to guide contributors towards behaviour that is consistent with the project and to do this in as light-a-weight way as possible.  The template covers 3 main areas:
1. A link to an issue - ideally we have atomic PRs so we have 1 issue and 1 resolving PR that should keep changes small and easier to review.  The issue serves as the problem description and discussion space for potential solutions.  In some circumstances there may not be an issue raised in which case the linked issue above could be replaced with a summary and description of the problem.  However, issue raising is preferred.
1. Description - this is …

feat: initial commit of PR template

---

src/agents/bee/prompts.ts

In certain scenarios, the underlying prompt template used to render empty lines in places where it wasn't expected.
Attaching test cases:

fix(bee-agent): rendering of empty lines in prompt

---

.env.template
README.md
examples/llms/providers/groq.ts
package.json
src/adapters/groq/chat.test.ts
src/adapters/groq/chat.ts
tests/e2e/adapters/groq/chat.test.ts
tests/e2e/utils.ts
yarn.lock

Closes: #
- Integrated Groq's LLM capabilities with the framework through the `GroqChatLLM` adapter.
- Added support for streaming and non-streaming language model operations.
- Implemented configurable parameters such as temperature, max tokens, and top_p.
- Enabled serialization and deserialization for state persistence.
- Added usage example and a readme update.

feat(groq-adapter): add groq adapter integration

---

src/adapters/shared/llmChatTemplates.ts

It seems like the official llama 3.1 implementation ends the prompt with `\n\n` before passing it for inference. Currently only single `\n` is passed. This has an effect on the inference output.
Supporting evidence:
- https://github.com/meta-llama/llama-models/blob/659a13ae2099748d23088fbf9293521de569dd8c/models/llama3/api/chat_format.py#L29
- https://dataplatform.cloud.ibm.com/docs/content/wsj/analyze-data/fm-prompt-samples.html?context=wx#sample7a0
- https://huggingface.co/meta-llama/Meta-Llama-3.1-70B-Instruct/blob/main/tokenizer_config.json

fix(llama-3-1): add trailing new line

---

package.json
prettier.config.js

Part of: #21 
One small step towards "Reduce number of files in project root #21" issue. Putting prettier settings in the package.json eliminates one file and works with IDEs, CLI, our yarn format[:fix], etc.  Some folks might prefer a separate file, but this seems pretty reasonable.

chore: Move prettier.config.js settings into package.json

---

docs/tools.md

Minor improvements to tools documentation. 
Tools doc needed some minor improvement.
Includes more info on tool description and a better schema example.
Adds a list of general tips for building tools.

docs(tool): Improve tools doc

---

.env.template
README.md
package.json
src/tools/search/googleCustomSearch.test.ts
src/tools/search/googleCustomSearch.ts
tests/e2e/utils.ts
yarn.lock

- Adding Google Custom Search Tool
- Updated Readme

feat(tool): add google custom search tool

---

CONTRIBUTING.md

Closes: #45 
Updating the CONTRIBUTING.md to indicate that we will be using DCO and signoff instead of having a CLA signed.

docs: use DCO instead of CLA in CONTRIBUTING.md

---

src/adapters/bam/chatPreset.ts
src/adapters/watsonx/chatPreset.ts
src/agents/bee/prompts.ts
src/agents/bee/runner.spec.ts
src/template.test.ts
src/tools/search/duckDuckGoSearch.ts
src/tools/search/wikipedia.ts

The PR improves agent behavior for llama 3.1 model:
- Improved tool selection (DuckDuckGo vs Wikipedia)
- Improved time awareness
- Improved capability to break complex tasks into smaller ones
- Improved capability to perform multiple function calling
- Better markdown support
- Improve question decomposition
- ...more

feat(bee-agent): update system prompt, tools description

---

src/internals/helpers/array.ts
src/tools/python/python.ts
src/tools/python/storage.ts

Change format of the JSON Schema in order to allow the LLM to easily comprehend what files are available and under which name

feat(code-interpreter): improve file input prompt

---

src/tools/python/python.ts
src/tools/python/storage.ts

Rename `hash` to signify that we no longer require this to be a content hash of the file.

feat(code-interpreter): rename "hash" to "pythonId"

---

README.md

Some links still went to old overview page, update links to point to specific pages to be consistent with references to other pages moved from the overview page and references to the same topic elsewhere in the README.md
Noticed a few links that still went to the overview that now just has entries pointing to specific pages.
Other references in the README.md to the same topics already pointed to the specific pages so update
to be consistent with that.
Closes: #
Updated links to point to the specific pages.

doc: fixup a few links

---

CONTRIBUTING.md
tests/utils/llmFactory.ts

Add support for using a local model for e2e testing.
Currently e2e testing requires a remote service which may cost people $ to run. Add the option
to use a model running locally if OLLAMA_HOST is set. If an API key is specified the associated
service will be used in preference to OLLAMA_HOST so this change should have no effect on
people not trying to use a local model.
If OLLAMA_HOST is set and no other API keys are providced use that host to run the e2e tests.

chore: support local model for running e2e tests

---

src/adapters/ibm-vllm/chatPreset.ts
src/adapters/shared/llmChatTemplates.ts

Update the granite 3 shared chat template to support tool messages. 
Reference: https://huggingface.co/ibm-granite/granite-3.0-8b-instruct/blob/main/tokenizer_config.json
This update paves the way for better granite bee support. 
1. Move the granite chat template to shared folder. 
2. Update the template with tool roles

Update the granite chat template for tools

---

README.md
docs/README.md

While reading some of the documentation I noticed some broken links.
During the build step the README.md is copied into the docs directory and the relative links cause failures.
Update top level README.md to use absolute links so that the file work both at the top level and in docs.
Closes: #

fix: fix broken links in docs README.md

---

CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
docs/CHANGELOG.md
docs/CODE_OF_CONDUCT.md
docs/CONTRIBUTING.md
docs/agents.md
docs/cache.md
docs/overview.md
examples/cache/slidingCache.ts

fixed typos in CHANGELOG.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, agents.md, cache.md, and overview.md
fixed link to make it clickable in CODE_OF_CONDUCT.md
Ref: #115 
- CHANGELOG.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- docs/agents.md
- docs/cache.md
- docs/overview.md
- CODE_OF_CONDUCT.md changed simple link to markdown link
i.e. from "https://www.contributor-covenant.org/faq" to "[www.contributor-covenant.org/faq](https://www.contributor covenant.org/faq)"
Signed-off-by: Anurag Verma <104461155+anurag-verma-india@users.noreply.github.com>

docs: fix typos in some docs files

---

.env.template
docs/tools.md
examples/agents/elasticsearch.ts
package.json
src/tools/database/elasticsearch.test.ts
src/tools/database/elasticsearch.ts
tests/e2e/utils.ts
tests/examples/examples.test.ts
yarn.lock

This pull request introduces a new ElasticSearchTool, to perform queries against ElasticSearch databases. This tool provides three actions:
1. LIST_INDICES: Lists all available indices in the ElasticSearch database, excluding system indices.
2. GET_INDEX_DETAILS: Retrieves detailed field mappings for a specified index.
3. SEARCH: Executes keyword search or aggregation queries on a specified index with pagination support.

feat(tool): add elasticsearch tool

---

src/agents/granite/agent.ts

Cant override the GraniteBeeAgent system prompt. 
Allows overriding of the granite agent system and assistant prompt. Useful for testing/experimentation with system prompt variations.

fix(agents): allow override granite bee prompts

---

src/adapters/ibm-vllm/llm.ts

The parameter `json_schema` is supposed to be a string, not object.

fix(adapters): vLLM JSON Schema guided decoding

---

docs/tools.md
examples/tools/custom/base.ts
examples/tools/custom/openLibrary.ts
src/adapters/langchain/tools.ts
src/tools/arxiv.ts
src/tools/base.test.ts
src/tools/base.ts
src/tools/calculator.ts
src/tools/custom.ts
src/tools/database/elasticsearch.ts
src/tools/database/milvus.ts
src/tools/database/sql.ts
src/tools/llm.ts
src/tools/python/python.ts
src/tools/search/duckDuckGoSearch.ts
src/tools/search/googleSearch.ts
src/tools/search/wikipedia.ts
src/tools/similarity.ts
src/tools/weather/openMeteo.ts
src/tools/web/webCrawler.ts

- Tools' base events are now typed and can be easily extended (this was not previously possible due to TS errors).
- Each tool will now has its own namespace instead of a default one.
⚠️ Breaking changes due to TS limitations.
- Emitter now must be defined manually for all new tools (base tool defines emitter as abstract).

feat(tools)!: improve type support for events

---

examples/agents/ibm_granite_bee.ts
src/adapters/ibm-vllm/chatPreset.ts

Closes: #190 
The backend ibmvllm model for granite has been updated to `ibm-granite/granite-3.0-8b-instruct` but retains the generic name `ibm/granite-instruct`. 
Thie fix corrects the name in the ibmvllm adapter.

fix: provide correct model id for granite vllm

---

src/agents/bee/agent.ts

Closes: #216 
Broadens the granite runner check to capture ollama model ids.
I worked on a more specific regex but ultimately I think a simple check for `granite` is simple, and sufficient until we determine that it isn't.

fix(agents): broaden the granite runner check

---

src/adapters/ibm-vllm/chatPreset.ts

Cant have a (dot) in ibmvllm backend model id, so the current ibmvllm model_id for granite is incorrect due to the inclusion of a (dot).
- Replaced the (dot) with a dash to match the backend model id.

fix(llms): correct the vllm granite model_id

---

src/agents/bee/runners/default/runner.ts
src/agents/bee/runners/granite/runner.ts

N/A
Reverts 41ea34f commit that introduced changes to constrained decoding that have negative impact on inference speed. It keeps whitespaces in place.

revert(agents): update constrained decoding for Bee

---

src/agents/bee/agent.ts
src/agents/bee/runners/base.ts
src/agents/bee/runners/default/runner.ts
src/agents/bee/runners/granite/runner.ts

- Delegate template handling to a runner
Closes: #219

feat(agents): use prompt templates from a concrete runner

---

src/instrumentation/create-telemetry-middleware.ts
src/instrumentation/helpers/create-span.ts

I increased the span's timestamp precision. The OpenTelemetry framework does not parse the Date objects correctly. 
The code is tested in the API and UI.

feat: (instrumentation): increase timestamp precision

---

package.json
src/adapters/ollama/chat.ts
src/adapters/ollama/llm.ts
src/adapters/ollama/shared.ts
tests/e2e/adapters/ollama/chat.test.ts
tests/e2e/adapters/ollama/test.ts
yarn.lock

Add support for newly introduced Ollama Structured Output.
**TODO: Verify whether the adapter works with Ollama version **below** 0.5 (`ollama --version`)**
```bash
OLLAMA_HOST="http://0.0.0.0:11434" CI=true yarn vitest tests/e2e/adapters/ollama/chat.test.ts
```

feat(llms): add ollama structured output support

---

examples/tools/llm.ts
src/agents/bee/runners/default/runner.ts
src/agents/experimental/replan/agent.ts
src/tools/base.ts
src/tools/llm.ts

- Propagate the agent's (runner) memory to the Tool's Run context
- Replace old (not used) LLMTool with a new one that uses provided LLM to accomplish agent's intent (it uses a custom system prompt + messages from the memory)
```ts
new LLMTool({
llm: BAMChatLLM.fromPreset("meta-llama/llama-3-8b-instruct"),
name: "LLM", // optional
description: "Uses expert LLM to work with data in the existing conversation (classification, entity extraction, summarization, ...)" // optional
template?: LLMTool.template // optional (system prompt)
})
```
`yarn start examples/tools/llm.ts`
```ts
import "dotenv/config";
import { BeeAgent } from "bee-agent-framework/agents/bee/agent";
import { createConsoleReader } from "examples/helpers/io.js";
import { FrameworkError } from "bee-agent-framework/errors"; …
```

feat(tools): use agent's memory within LLM Tool

---

src/instrumentation/helpers/utils.ts

Closes: https://github.com/i-am-bee/bee-observe/issues/17
I cannot use `Object.prototype.hasOwnProperty.call` detection in my case, which is used in the `hasProp` function witch is used in the `getProp` function. 
The custom detection is tested and runs well.

fix(instrumentation): assert raw prompt

---

src/tools/weather/openMeteo.ts
tests/e2e/tools/openMeteo.test.ts

If the llm uses the openMeteo tool with a startDate in the future, but does not specify an endDate then the endDate is set to now which is prior to the start date. This causes the the service to throw an error. 
Check of the end data is prior to the start date, if so reset the end date.

fix(tools): verify that the end date is later than the start date

---

README.md
docs/README.md
examples/README.md
examples/agents/granite/README.md
examples/agents/granite/granite_bee.ts
examples/agents/granite/granite_wiki_bee.ts
examples/llms/embed.ts
src/agents/bee/prompts.ts
src/agents/bee/runners/default/runner.ts
src/agents/bee/runners/granite/prompts.ts
src/agents/bee/runners/granite/runner.ts
src/internals/helpers/math.ts

1. Granite example agents now have their own folder (`examples/granite`)
2. Moved the granite docs from the `/docs` to to a `README.md` inside of `examples/granite` so we can link directly to the README and the code examples (cookbook)
3. Added another example granite agent using retrieval with the wikipedia tool and updated documentation
4. Fixed an issue where default runner was not picking up templates from the templates method, and thus could not be over ridden in the granite runner subclass
5. Updates to granite system prompt (simplification), added time + date into the system prompt
6. Custom granite user template (remove createdAt) and custom granite tool prompts
7. Fixed an issue where the granite available tools were being double json encoded
8. Added an embedding example
9. …

fix(agents): granite agent fixes, update granite docs and examples

---

examples/llms/providers/ibm-vllm.ts
package.json
scripts/ibm_vllm_generate_protos/ibm_vllm_generate_protos.sh
scripts/ibm_vllm_generate_protos/tsconfig.proto.json
scripts/ibm_vllm_generate_protos/tsup.config.ts
src/adapters/ibm-vllm/chat.ts
src/adapters/ibm-vllm/client.ts
src/adapters/ibm-vllm/llm.ts
src/adapters/ibm-vllm/proto/caikit_data_model_caikit_nlp.proto
src/adapters/ibm-vllm/proto/caikit_data_model_common.proto
src/adapters/ibm-vllm/proto/caikit_data_model_nlp.proto
src/adapters/ibm-vllm/proto/caikit_data_model_runtime.proto
src/adapters/ibm-vllm/proto/caikit_runtime_Nlp.proto
src/adapters/ibm-vllm/types.ts
src/internals/types.ts
tests/e2e/adapters/ibm-vllm/llm.test.ts
yarn.lock

feat(adapters): add embedding support for IBM vLLM

---

src/agents/bee/runners/default/runner.ts
src/agents/bee/types.ts

Extends the Bee 'start' event to allow on-fly modifications.
Usage:
```typescript
const agent = new BeeAgent(...)
agent.emitter.on("start", async ({ memory, tools, meta }) => {
console.log(`Iteration: ${meta.iteration}`);
const lastMessage = memory.messages.at(-1);
if (lastMessage?.text.includes("weather")) {
tools.splice(0, Infinity, ...tools.filter((tool) => tool.name.includes("weather")));
}
});
```
Ref: #184

feat(agents): extend bee start event

---

.github/PULL_REQUEST_TEMPLATE.md

N/A
Adds an item to the pull request template for contributors to sign off on their commits

docs: add signing off on commits to PR template

---

examples/agents/granite/README.md
examples/agents/granite/granite_bee.ts
examples/agents/granite/granite_wiki_bee.ts
src/adapters/ibm-vllm/chatPreset.ts
src/adapters/shared/llmChatTemplates.ts
src/adapters/watsonx/chatPreset.ts
src/agents/bee/runners/granite/prompts.ts
src/agents/bee/runners/granite/runner.ts

Contributes-to: https://github.com/i-am-bee/internal/issues/19
Adds support for Granite 3.1. Drops 3.0 support.
Updates granite examples.
This needs to be merged on Wed 18th to coincide with broader release.

feat(agents): granite 3.1 support

---

docs/tools.md
package.json
src/tools/openapi.test.ts
src/tools/openapi.ts
tests/e2e/tools/openapi.test.ts
yarn.lock

Add OpenAPI tool

---

.github/workflows/main.yml
.gitignore
.husky/pre-commit
eslint.config.js
package.json
scripts/copyright.sh
scripts/ibm_vllm_generate_protos/ibm_vllm_generate_protos.sh
src/adapters/ibm-vllm/proto/caikit_data_model_caikit_nlp.proto
src/adapters/ibm-vllm/proto/caikit_data_model_common.proto
src/adapters/ibm-vllm/proto/caikit_data_model_nlp.proto
src/adapters/ibm-vllm/proto/caikit_data_model_runtime.proto
src/adapters/ibm-vllm/proto/caikit_runtime_Nlp.proto
src/adapters/ibm-vllm/proto/generation.proto
src/agents/bee/runners/default/runner.ts
src/agents/bee/runners/granite/runner.ts
src/agents/parsers/linePrefix.ts
src/tools/openapi.test.ts
yarn.lock

- Runs COPYRIGHT check in Github Action.
- Automatically runs COPYRIGHT script via `lint-staged,` but prevents failing if `nwa` package is not available.
- Runs documentation links check only if some Markdown file has changed (locally only).
- Enable DCO bot
Ref: #259

chore: simplify contribution process

---

src/instrumentation/tracer.ts

I added the `traceId` attribute to each span. I will use it in the Observe for optimised span loading. 
Must be merged with https://github.com/i-am-bee/bee-observe/pull/25

feat(instrumentation): trace id for each span

---

docs/tools.md
examples/README.md
examples/tools/mcp.ts
package.json
src/internals/helpers/paginate.test.ts
src/internals/helpers/paginate.ts
src/tools/mcp.test.ts
src/tools/mcp.ts
src/tools/search/duckDuckGoSearch.ts
src/tools/search/googleSearch.ts
yarn.lock

Closes: #238 
This PR introduces support for [MCP Tool](https://modelcontextprotocol.io/docs/concepts/tools).

feat(tools): add Model Context Protocol tool

---

docs/README.md
docs/_sidebar.md
docs/tutorials.md

Signed-off-by: Tomas Pilar <tomas.pilar@apoco.com>
Closes: #

docs: add Slack tutorial

---

typescript/src/adapters/ollama/backend/client.ts

Fixes #319
#319
Closes: #
Removed the settings parameter as it was not being passed from the base adapters.
Started taking base URL from this.settings.baseURL (if present.)

fix(adapters): ollama adapter to use client settings and base url

---

python/pyproject.toml
python/scripts/absolute_links.py
python/scripts/copyright.sh

Pypi needs absolute links in README.md to display them correctly.
Closes: #346

docs: use absolute links for Pypi

---

python/beeai_framework/agents/runners/default/runner.py
python/examples/agents/bee.py

Emits parsed react constructs such as thought, tool_input etc from the line parser.

fix: emit parsed react elements

---

python/beeai_framework/adapters/litellm/chat.py
python/beeai_framework/agents/base.py
python/beeai_framework/agents/runners/default/runner.py
python/beeai_framework/backend/chat.py
python/beeai_framework/backend/message.py
python/beeai_framework/context.py
python/beeai_framework/emitter/emitter.py
python/beeai_framework/emitter/types.py
python/examples/agents/bee.py
python/examples/agents/granite.py
python/examples/agents/simple.py

This follows up on a handful of PRS: #359 #343 and some work from before the push to the monorepo
This fixes the following:
- some return type issues in `Message`, found when testing examples
- missed references to input_schema (from #343), the alias only works when treating the class as a dict
- a bit of TS parity in BaseAgent
- fix `frozen=True` on a couple BaseModels (as in #359) (I implemented it wrong the first time around)
- update Emitter.on callbacks to allow synchronous functions (as in #359), plus updates to affected callbacks
- allow Emitter.observe callbacks to be synchronous (inspired by the above change), plus updates to affected callbacks

fix: various bug fixes

---

python/beeai_framework/adapters/litellm/chat.py
python/beeai_framework/adapters/ollama/backend/chat.py
python/beeai_framework/adapters/watsonx/backend/chat.py
python/beeai_framework/backend/chat.py
python/examples/backend/providers/watsonx.py

Closes: #377 
this PR updates how the `settings` parameters is handled and passed through to subsequent functions. it should allow for `base_url` and other parameters to be defined and properly propagated, e.g.,
```
llm = OllamaChatModel("llama3.1", settings={"base_url": "http://127.0.0.1:11444"})
```
```
llm = WatsonxChatModel(
"ibm/granite-3-8b-instruct",
settings={
"project_id": "WATSONX_PROJECT_ID",
"api_key": "WATSONX_API_KEY",
"api_base": "WATSONX_API_URL",
},
)
```

fix: pass through chatmodel params

---

python/.env.example
python/beeai_framework/adapters/ollama/backend/chat.py
python/tests/backend/test_chatmodel.py

Closes: #387
Allow connection to a different Ollama server through env vars (and add tests).

fix: ability to specify external Ollama server

---

typescript/src/workflows/workflow.test.ts
typescript/src/workflows/workflow.ts

Closes: #444  
Related to #463 in python 🐍  
This corrects in Typescript Workflow when the .addStep callback returned either SELF or PREV. It was trying to assign the appropriate subsequent step relative to the array of steps rather than the member representing the current step of the workflow.
eca19e fix: assign subsequent step relative to current step in Workflow
b9c26a test: add tests for workflow step changes
c61618: chore: lint and format workflow test

fix: index workflow with step definitions - typescript

---

python/beeai_framework/workflows/workflow.py
python/tests/workflows/test_workflow_nav.py

FIxes a potential issue that can occur based on how we navigate workflow steps by using the executed step history. 
The fix is to transition based on the user defined step definitions, rather than the execution history. Also includes a testcase that recreates the issue. 
Ref #444

fix: index workflow with step definitions

---

python/pyproject.toml

Verify that the local branch is up to sync with the origin before releasing.

chore: update release script

---

python/beeai_framework/agents/runners/base.py
python/beeai_framework/agents/types.py
python/beeai_framework/template.py

Closes: #385
Update `PromptTemplate.render` to accept a `TemplateInput` schema object, a schema `dict`, or the schema values as `kwargs` for more flexibility for users
Also does some followup cleanup from #462 in relation to `PromptTemplate.fork`

fix(agents): improve PromptTemplate.render API

---

typescript/src/internals/helpers/hash.ts

Closes: #478 
Switch from SHAKE256 to SHA256 and a manual slice. As far as I can see, the "arbitrary length" feature of shake256 is not used anywhere, but to prevent accidental misuse I added a `NotImplemented` guard.
Not sure how to best test this fix, let me know your thoughts.

fix: make `createHash` work in Electron.

---

python/beeai_framework/tools/mcp_tools.py
python/beeai_framework/tools/search/base.py
python/beeai_framework/tools/search/duckduckgo.py
python/beeai_framework/tools/search/wikipedia.py
python/beeai_framework/tools/tool.py
python/beeai_framework/tools/weather/openmeteo.py
python/docs/tools.md
python/examples/notebooks/agents.ipynb
python/examples/tools/custom/base.py
python/examples/tools/custom/openlibrary.py
python/tests/tools/test_decorator.py
python/tests/tools/test_emitter.py

Adds a required emitter property on tools. All tool implementations now need to implement this property- providing an emitter instance.
I suggest we also change our tool implementations so that name, description and input_schema are implemented in the same manner for consistency. 
I also fixed a bunch of mypy errors in the code that I touched.

fix: emitter required for tools

---

python/docs/emitter.md
python/examples/emitter/base.py

emitters/base.py example added a listener on the root emitter, which was breaking all tests where it would later emit since all the tests share the root Emitter. This was caused by a descrepancy with how TS runs

test(examples): fix emitters/base.py example breaking e2e tests

---

python/beeai_framework/adapters/langchain/tools.py
python/beeai_framework/context.py
python/beeai_framework/tools/mcp_tools.py
python/beeai_framework/tools/search/duckduckgo.py
python/beeai_framework/tools/search/wikipedia.py
python/beeai_framework/tools/tool.py
python/beeai_framework/tools/weather/openmeteo.py
python/docs/tools.md
python/examples/notebooks/agents.ipynb
python/examples/notebooks/workflows.ipynb
python/examples/tools/custom/base.py
python/examples/tools/custom/openlibrary.py
python/tests/tools/test_decorator.py
python/tests/tools/test_emitter.py

1. Replaces to_string on tool output with python __str__ override
2. Tool results are now printed in agents notebook
3. Decorated tools that return str can now work with Agent (output is wrapped as StringToolOutput)
4. Error checking in notebooks for search tool failures

fix: improve decorated tool output

---

python/beeai_framework/tools/weather/openmeteo.py

fix(tools): handle non-existing locations in OpenMeteo

---

python/beeai_framework/agents/base.py
python/beeai_framework/agents/react/agent.py
python/beeai_framework/agents/react/runners/base.py
python/beeai_framework/agents/react/runners/default/runner.py
python/beeai_framework/agents/react/runners/granite/runner.py
python/beeai_framework/agents/react/types.py
python/docs/agents.md
python/examples/agents/custom_agent.py
python/tests/runners/test_default_runner.py

Ref #433 
This is an initial pass at addressing the mypy results for `beeai_framework/agents/*`
The primary change is adding `IN`, `OPT`, `OUT` generics to `BaseAgent`, though until we address #455 the `IN` and `OPT` are essentially hard coded to `{"prompt": prompt}` and `{"execution": execution, "signal": signal}`

refactor(agents): Add generics to BaseAgent and other mypy fixes

---

python/beeai_framework/context.py
python/examples/agents/granite.py
python/examples/agents/react.py
python/examples/agents/simple.py

Closes: #471
This introduces the `Run.on` method that combines the `Run.observe` and `Emitter.match` calls into one more user friendly callback.
Included in this PR:
- The `Run.on` method and rework of `Run` internals to support it
- Updates to a few demos to leverage the new method
- Address mypy errors by moving the `ContextVar` storage to a global, as a `ContextVar` is intended to be

feat: Add Run.on API to directly add an event callback

---

typescript/examples/backend/chatFromName.ts
typescript/src/backend/utils.ts

Fix that makes it possible to use model ids with colon symbols which is common in ollama.
For example: 
```
const llm = await ChatModel.fromName("ollama:granite3.2:8b");
```
The current implementation will identify `granite3.2` as the modelId and lead to an ollama error. 
This PR updates the model parsing code to correctly extract the model id `granite3.2:8b`

fix: handle colon symbols in model id

---

python/docs/backend.md
python/examples/agents/experimental/human.py
python/examples/backend/providers/watsonx.py
python/examples/tools/experimental/human.py

Ref #336 
This adds the remaining examples that aren't blocked by a missing feature, Tool, or Agent
Examples added:
- `watsonx_debug` added to `backend/providers/watsonx.py` instead of it's own file
- `tools/experimental/human.py` and `agents/experimental/human.py` added as a pair

test(examples): Add missing examples

---

.github/workflows/docs.yml
python/docs/cache.md
python/docs/serialization.md
typescript/CONTRIBUTING.md
typescript/README.md
typescript/docs/cache.md
typescript/docs/overview.md
typescript/docs/serialization.md
typescript/docs/tools.md

Solved https://github.com/i-am-bee/beeai-framework/issues/543.
Updated links to existing docs. 
Now, as per link checker, the missing links are only 
Errors in docs/README.md
But, this is an issue with fragments. The links are working fine with readme, IDE and website. The link-checker has an issue with finding anchor links in the code. So I will mention this in the PR submitted https://github.com/i-am-bee/beeai-framework/pull/542
Closes: #543 

docs: fix remaining broken links for both typescript and python   @bhargavyagnik

---

python/beeai_framework/tools/mcp_tools.py
python/beeai_framework/utils/models.py
python/tests/utils/test_json_schema.py

Closes: #553 
this PR updates the result returned by the MCP tool. more specifically, how the MCP tool_call result is transformed into the JSONToolOutput.
this resolves the following error seen when the json schema contains an optional field which is not included by the tool_input
```
Agent 🤖 :  ToolError(beeai_framework.tools.errors): Tool Error
ExceptionGroup(builtins): unhandled errors in a TaskGroup (1 sub-exception)
...
LinePrefixParserError(beeai_framework.parsers.line_prefix): The generated output does not adhere to the schema.
Value for 'tool_input' cannot be retrieved because its value does not adhere to the appropriate schema.
```

fix: mcp tool error

---

python/beeai_framework/adapters/litellm/chat.py
python/beeai_framework/adapters/litellm/utils.py
python/beeai_framework/adapters/openai/backend/chat.py
python/docs/backend.md
python/tests/backend/providers/test_litellm_utils.py

Closes: #532
[ Updated with revised format / variable ]
Adds support for LiteLLM provider to add additional headers
```
export OPENAI_EXTRA_HEADERS="MY_API_KEY=ab592c9f3e001b"
```
To test (for example, with OpenAI, also set:
```
OPENAI_API_KEY=my-api-key
OPENAI_CHAT_MODEL=my-model
OPENAI_API_BASE=https://my-endpoint/
```
Tested ok

feat(adapters): Support additional headers for OpenAI backend

---

python/beeai_framework/tools/mcp_tools.py
python/docs/tools.md
python/examples/tools/mcp_agent.py
python/examples/tools/mcp_tool_creation.py
python/tests/tools/test_mcp_tool.py

Signed-off-by: Tomas Pilar <tomas.pilar@apoco.com>
Closes: #566 

fix(tools): avoid session management in mcp tool

---

python/beeai_framework/agents/errors.py
python/beeai_framework/backend/errors.py
python/beeai_framework/emitter/errors.py
python/beeai_framework/errors.py
python/beeai_framework/logger.py
python/beeai_framework/memory/errors.py
python/beeai_framework/template.py
python/beeai_framework/tools/errors.py
python/beeai_framework/utils/errors.py
python/beeai_framework/workflows/errors.py
python/docs/errors.md
python/examples/errors/base.py
python/tests/errors_test.py

Closes: #510
Adds support for additional 'context' to be associated with an error.
Updated implementation, docs, testcase, example
Example output (from the base error example):
```
(beeai-framework-py3.13) ➜  python git:(context) ✗ /Users/jonesn/AI/bee/beeai-framework/python/.venv/bin/python /Users/jonesn/AI/bee/beeai-framework/python/examples/errors/base.py
Message: Function 'getUser' has failed.
Meta: fatal:True retryable:False
Cause: User with Given ID Does not exist!
FrameworkError(beeai_framework.errors): Function 'getUser' has failed.
FrameworkError(beeai_framework.errors): Cannot retrieve data from the API.
ValueError(builtins): User with Given ID Does not exist!
Context: {'workflow': 'activity_planner', 'provider': 'ollama', 'chat_model': 'granite3.2:8b'}
```
STILL TO DO
**Note …

chore(internal): Support context dictionary in FrameworkError

---

python/beeai_framework/adapters/litellm/chat.py

Watsonx does not handle empty array of tool calls.

fix(backend): do not pass empty tool calls to Watsonx

---

python/beeai_framework/adapters/litellm/chat.py
python/beeai_framework/adapters/ollama/backend/chat.py
python/poetry.lock

fix(backend): do not use OpenAI strict response format for Ollama

---

python/beeai_framework/tools/events.py
python/beeai_framework/tools/tool.py

Ref: #603
The current implementation is using an invalid configuration for Pydantic models. `attr: BaseModel` is not invalid and should be replaced with `attr: InstanceOf[BaseModel]` to accept an arbitrary Pydantic model. This bug prevented us from logging the tool's events.
**Changes**
- Fix tools events serialization
- Propagate correct parameters to tool events

fix(tools): update events definition to pass Pydantic validation

---

python/.env.example
python/beeai_framework/adapters/amazon_bedrock/backend/README.md
python/beeai_framework/adapters/amazon_bedrock/backend/chat.py
python/beeai_framework/adapters/openai/backend/chat.py
python/beeai_framework/adapters/vertexai/backend/chat.py
python/beeai_framework/adapters/watsonx/backend/chat.py
python/docs/backend.md
python/examples/llms.py
python/tests/backend/test_chatmodel.py
python/tests/examples/test_examples.py

Closes: #527
Updates environment variables to follow [typescript](https://github.com/i-am-bee/beeai-framework/blob/main/typescript/docs/backend.md) as close as possible
In all cases explicit entries in the settings dict take precedence. 
If neither are set, the LiteLLM variables will initialize that value
Note we don't have any embedding model support, so those variables are omitted.
The typescript implementations do have some extra variables such as url. These have been omitted where there's no reference in the litellm documentation to this support. (not tried adding these settings)
Each provider has been tested with a basic configuration, but not a broad set of configuration options.
In typescript we use `WATSONX_REGION` from which the base URL is determined
In python we did use the …

Align backend environment variable usage with typescript (>> LiteLLM)

---

python/beeai_framework/adapters/litellm/chat.py

Closes: #609
We were looking for the usage data in the wrong place, this updates it to look in the correct location and properly types usage now it is no longer always None

fix(adapters): actually return usage in ChatModelOutput

---

python/.env.example
python/beeai_framework/adapters/amazon_bedrock/backend/chat.py
python/beeai_framework/adapters/anthropic/backend/chat.py
python/beeai_framework/adapters/azure_openai/backend/chat.py
python/beeai_framework/adapters/vertexai/backend/chat.py
python/docs/backend.md

Closes: #586
Adds support for extra headers to:
- Azure OpenAI
- Anthropic
- Amazon Bedrock
- Google VertexAI
In the above cases support for *extra_headers* is documented in the LiteLLM docs and/or found from a code scan
Changes were not made to
- Ollama (note there is a [PR](https://github.com/BerriAI/litellm/pull/7180) open)
- WatsonX
- Groq
- XAI
due to lack of support in liteLLM.
- OpenAI adapter already has support
Testing
**IN PROGRESS**
No test is made that the extra headers have any effect on the actual provider.

feat(adapters): Add support for extra headers to more backend providers

---

python/beeai_framework/agents/react/runners/default/runner.py
python/beeai_framework/tools/code/sandbox.py
python/docs/tools.md
python/poetry.lock
python/tests/examples/test_examples.py

Related to #683 
While testing https://github.com/i-am-bee/beeai-framework-py-starter/blob/main/beeai_framework_starter/agent_code_interpreter.py I was hitting the following error:
```
SandboxToolExecuteError(beeai_framework.tools.code.sandbox): Framework error
Context: {"name": "get_riddle"}
AttributeError(builtins): 'ToolRunOptions' object has no attribute 'env'
```
which I was able to trace back to https://github.com/i-am-bee/beeai-framework/blob/58f17bcc8c1e3065db6040055fa524f7c1ad8a60/python/beeai_framework/tools/code/sandbox.py#L80
This is because `ToolRunOptions` is being passed in rather than the expected `SandboxToolOptions`.
This removes the unnecessary `ToolRunOptions` initialization in `DefaultRunner`
/ [TypeScript](https://github.com/i-am-bee/beeai-framework/blob/main/CONTRIBU …

fix(tools): SandboxTool fails when run by an agent

---

python/beeai_framework/tools/code/python.py
typescript/src/tools/custom.test.ts
typescript/src/tools/python/python.ts

Ref: #688 
remove branding from code interpreter references

chore(tools): remove branding from code interpreter references

---

python/beeai_framework/adapters/litellm/chat.py
python/beeai_framework/adapters/ollama/backend/chat.py
python/beeai_framework/adapters/watsonx/backend/chat.py
python/beeai_framework/backend/chat.py
python/beeai_framework/backend/message.py
python/beeai_framework/backend/types.py
python/beeai_framework/backend/utils.py
python/beeai_framework/utils/strings.py
python/examples/backend/providers/ollama.py
python/poetry.lock
python/pyproject.toml

Closes: #689
This PR does the following:
- simulate `tool_choice=required` and `tool_choice=my_tool` for environments where it is not supported
- adds tool calling capabilities to those for which their providers do not support it (eg: deepseek), by setting `model_supports_tool_calling=False` and `tool_choice=required` or `tool_choice=my_tool`
- improve schema parsing
- refactor ChatModelKwargs
- fix dict parsing in UserMessage

fallback to structured decoding in environments without proper tool choice support

---

python/beeai_framework/agents/react/events.py
python/beeai_framework/agents/react/runners/base.py

fix(agents): remove extra ` in the group_id

---

python/beeai_framework/agents/react/__init__.py
python/beeai_framework/agents/react/events.py
python/beeai_framework/agents/react/runners/default/runner.py
python/docs/events.md

Followup to #726
Removes the remaining references to `ReActAgentToolEvent`

chore: cleanup unused emitter event

---

python/beeai_framework/adapters/litellm/chat.py
python/beeai_framework/adapters/ollama/backend/chat.py

TypeError when trying to clone a chatmodel:
```
TypeError: beeai_framework.adapters.litellm.chat.LiteLLMChatModel.__init__() got multiple values for keyword argument 'provider_id'
```
Closes: #
TypeError when trying to clone a chatmodel:
```python
async def main() -> None:
model = OllamaChatModel(model_id="llama3.1")
return await model.clone()  # throws an error
```
error thrown:
```
TypeError: beeai_framework.adapters.litellm.chat.LiteLLMChatModel.__init__() got multiple values for keyword argument 'provider_id'
```

fix: typeerror when cloning chatmodel

---

python/beeai_framework/adapters/langchain/tools.py
python/beeai_framework/agents/experimental/remote/agent.py
python/beeai_framework/tools/mcp/mcp.py
python/beeai_framework/tools/search/duckduckgo/duckduckgo.py
python/beeai_framework/tools/search/wikipedia/wikipedia.py

Ref: #807
Closes: #
On some Unix/Linux shells, such as zsh, square brackets `[` and `]` are pre-processed by the shell and not handed over to the pip command, resulting in a confusing error statement such as:
```sh
$ pip3 install beeai-framework[wikipedia] --dry-run
zsh: no matches found: beeai-framework[wikipedia]
```
This PR clarifies the installation command by including quotes to stop shells from pre-processing the command, and passing it as-is to pip to run.

docs(tools): clarify pip install message

---

python/tests/examples/test_examples.py

#810 added a couple new examples for ACP, but didn't add both the to example test whitelist, causing the e2e tests to fail if the platform is not running

test(examples): Address failing e2e test

---

python/beeai_framework/adapters/watsonx/__init__.py

I was using the watsonx embeddings support and realized that the `WatsonxEmbeddingModel` is not exposed for use by library users. 
Expose `WatsonxEmbeddingModel` from the watsonx backend module.

fix: expose watsonx embedding model

---

python/beeai_framework/utils/dicts.py
python/beeai_framework/utils/models.py
python/tests/utils/test_json_schema.py

feat: add support for oneOf/anyOf modifiers in the JSONSchemaModel

---

python/pyproject.toml

When I've installed llama-index I was getting an error from mypy about a conflict in the workflows module:
```
[python:check:mypy] $ poetry run mypy --show-error-context --pretty .
beeai_framework/workflows/__init__.py: error: Source file found twice under different module names: "beeai_framework.workflows" and "workflows"
```
After careful evaluation I've traced the error to naming conflict in `mypy` between two `workflows` modules:
1. from llama_index package where a top-level workflows module exist
2. from beeai_framework.workflows
This is not a problem from python point of view, but would happen with every future conflict.
`mypy` will treat every module in its `mypy_path` path as both top and relative path module, i.e. for `workflows` in `$MYPY_CONFIG_FILE_DIR/beeai_framework` we get …

fix: remove mypy path in project config

---

docs/modules/rag.mdx

The originally chosen icon from Lucide is not available on Mintlify, swapping to an existing one

docs: change RAG icon on documentation

---

docs/modules/rag.mdx
python/beeai_framework/adapters/langchain/backend/text_splitter.py
python/beeai_framework/backend/constants.py
python/beeai_framework/backend/text_splitter.py
python/examples/agents/rag_agent.py

This feature implements the text splitter abstraction for RAG and provides a LangChain integration
This brings us to the point where there are no external imports in the rag agent example

feat(backend): Adding text splitter backend class

---

python/beeai_framework/adapters/litellm/chat.py

Initialize `tool_choice` with `input.tool_choice` before conditional overrides to prevent undefined variable when tool_choice is supported but doesn't match specific conditions.

fix(adapters): initialize tool_choice in LiteLLM chat adapter

---

python/beeai_framework/utils/strings.py

Sets are not JSON serializable, so running `to_json(set())` ends with an infinite recursion.
I'm not sure if converting to a list is the best solution - is it ok that `from_json(to_json(set())) != set()`?

fix(internals): fix serialization of sets
