README.md
adding some contexts around of the example + fix minor typos
=> Update README.md adding context to run example

.github/workflows/release.yml
slackbot for GitHub releases
Closes: #
=> ci: add slackbot release notification

src/agents/bee/prompts.ts
Continuous system prompt improvements driven by various test cases.
=> feat(agent): update bee system prompt

src/tools/search/wikipedia.ts, tests/e2e/tools/wikipedia.test.ts
- instead of remove links - we unwrap them
- remove Wikipedia boxes unrelated to the content
- remove infobox
- correctly preprocess elements on all levels
- update the test regex
=> feat(tools): improve wikipedia parsing

infra/bee-code-interpreter/k8s/bee-code-interpreter.yaml, src/tools/python/output.ts, src/tools/python/python.ts
Allow running many new CLI tools and Python libraries made available through the latest Code Interpreter executor image. Plus some prompt optimization. Code Interpreter now runs Xonsh -- a syntatic extension over Python bringing shell compatibility -- which allows the LLM to write shell commands directly and subsequently not get lost in the double escaping.
=> feat: improve Python tool

src/tools/python/python.ts
Agent could not understand how to (not) use the IDs, so we just don't give the IDs to the agent anymore.
This has some implications regarding uniqueness of filenames, since we essentially use them as IDs now (among the results of `storage.list()`). Having these be unique used to be a soft requirement anyway, since the agent could not differentiate between files with the same name either way. The PR is written in a way where it does not matter whether `storage.list()` returns results with non-unique filenames, it just arbitrarily picks one of the results.
We should probably follow up by either forbidding upload of non-unique filenames to a conversation, or by auto-deduplicating (like browser downloads do).
Note that we still use the ID as a part of the link in the output. This does not …
=> fix(code-interpreter): prevent agent from misusing IDs

README.md, docs/README.md
=> docs: update README.md

src/tools/base.test.ts, src/tools/base.ts
Closes: https://github.com/i-am-bee/bee-agent-framework/issues/77
Adds additional validation for construction of dynamic tools.
=> feat: add additional validation for DynamicTool

docs/tools.md
Related to:
Refs: https://github.com/i-am-bee/bee-agent-framework/pull/100
Refs: https://github.com/i-am-bee/bee-agent-framework/issues/77
Updates documentation to reflect recent validation added.
=> chore: document DynamicTool validation

.github/CODEOWNERS
CODEOWNERS restriction is not being applied
Closes: #
=> fix(GH): update CODEOWNERS

src/tools/search/wikipedia.test.ts, src/tools/search/wikipedia.ts
=> feat(tool): improve wikipedia results filtering

examples/agents/bee_advanced.ts, src/internals/helpers/paginate.test.ts, src/internals/helpers/paginate.ts, src/tools/search/duckDuckGoSearch.test.ts, src/tools/search/duckDuckGoSearch.ts, src/tools/search/googleSearch.test.ts, src/tools/search/googleSearch.ts, tests/e2e/agents/bee.test.ts, tests/e2e/tools/duckDuckGoSearch.test.ts
=> feat(tool)!: remove pagination from GoogleSearch and DuckDuckGo

CONTRIBUTING.md, package.json
Closes: #49 
Based on the discussion in #49.  The current list of scopes are in https://github.com/i-am-bee/bee-agent-framework/issues/49#issuecomment-2400490099
=> ci: define commit scope values

docs/README.md, examples/agents/bee_granite.ts, src/adapters/watsonx/chatPreset.ts, src/agents/granite/agent.ts, src/agents/granite/prompts.ts, src/agents/granite/runner.ts
partially fixes: #145
GraniteBeeAgent and runner that implements the granite tool pattern.
=> feat(agents): granite agent

README.md, docs/README.md, docs/agents.md, examples/README.md, examples/agents/granite/chat.ts, examples/agents/granite/single_turn.ts
Docs for granite bee.
1. Added a section in the agents doc that addresses Granite 3.0 support, linked from the main README.
2. Put the granite examples in their own directory and added a new single turn example.
=> docs(agents): examples and docs for granite bee

examples/llms/providers/customChatProvider.ts, examples/llms/providers/customProvider.ts
There are minor changes necessary in the custom(Chat)Provider.ts when a new adapter is added. 
The custom(Chat)Providers are referred as the sample (or base) when a new adapter is added.  The minor changes in this PR may improve the user (or contributor) experiences.
=> Minor updates in custom(Chat)Provider examples

src/tools/database/sql.test.ts, src/tools/database/sql.ts, tests/e2e/tools/database/sql.test.ts
Ref: https://github.com/i-am-bee/bee-agent-framework/issues/173
SQLTool enhanced to minimize the number of iterations. Additionally, the tool now guides the LLM to add the schema name as a prefix to table names. This update includes:
**1. Minimized Number of Iterations**
Reduced the overall number of iterations required for the LLM to generate the correct SQL query by introducing two-steps action space.
**2. Schema Prefix Guidance**
Enhanced the tool to guide the LLM in automatically adding the schema name as a prefix to table names, improving query generation accuracy and compatibility with multi-schema databases.
=> feat(tools): enhance sql tool

docs/llms.md, examples/llms/providers/bedrock.ts, package.json, src/adapters/bedrock/chat.test.ts, src/adapters/bedrock/chat.ts, tests/e2e/utils.ts, tests/examples/examples.test.ts, yarn.lock
Ref: https://github.com/i-am-bee/bee-agent-framework/issues/122
Adding AWS Bedrock as inference provider.
=> feat(adapters): add aws bedrock

src/adapters/vertexai/chat.ts, src/adapters/vertexai/llm.ts, src/adapters/vertexai/utils.ts
Closes: #141 
Fix issues pointed out in this [comment](https://github.com/i-am-bee/bee-agent-framework/issues/141#issuecomment-2501034584)
=> fix(adapters): gcp vertexai llm adapter parameters

src/agents/bee/prompts.ts, src/agents/bee/runners/granite/prompts.ts, src/agents/bee/runners/granite/runner.ts, src/agents/bee/types.ts
Retry if LLM generates something that does not adhere to the communication structure defined in the system prompt.
TODOs:
- improves the "error" prompt
- consider using another "role"
- consider whether to remove the message after successful generation or not
=> feat(agents): retry on a parser error

src/agents/bee/prompts.ts
Improve tool usage for OpenAI models.
Note: Please do the complex evaluation @jezekra1
=> feat(agents): update system prompt for Bee

CONTRIBUTING.md, docs/llms.md
This was missing in #201 
https://github.com/i-am-bee/bee-agent-framework/pull/201#pullrequestreview-2475048765
=> Add AzureOpenAI in docs

.env.template, docs/ibm-granite.md
Contributes-to: https://github.com/i-am-bee/internal/issues/19
Provides accompanying "cookbook" style documentation for the [ibm_granite_bee](https://github.com/i-am-bee/bee-agent-framework/blob/main/examples/agents/ibm_granite_bee.ts) example agent.
=> feat: add granite bee documentation

src/agents/experimental/streamlit/prompts.ts
- remove emoji
- improve generating of `main()` method
- introduce two-parameter variant of `st.title()`
=> feat(agents): update streamlit agent prompt

src/adapters/ibm-vllm/chatPreset.ts, src/adapters/watsonx/chatPreset.ts
Contributes-to: https://github.com/i-am-bee/internal/issues/19
Adds preset support for the Granite 3.1 models.  This PR deliberately does not include examples/documentation at this stage as these will follow later once testing of the new models has completed.
=> feat: presets for Granite 3.1

src/agents/experimental/streamlit/prompts.ts
- Instruct to use HTTPS for fetch calls (can't fetch HTTP from a HTTPS site).
- Be more explicit about not running `main()` manually (it kept trying to run `asyncio.run` and similar).
- Give more communication directives on how to interact with the user.
=> feat(agents): improve streamlit agent prompt

examples/agents/granite/README.md, examples/agents/granite/granite_wiki_bee.ts
Minor tweaks to the granite cookbook to coincide with the llama model release. 
1. Prompt change
2. Ollama parameter change
3.
=> fix: modify params on ollama granite cookbook

src/tools/similarity.ts
=> feat(tools): add minScore filter condition for SimilarityTool

src/adapters/bedrock/chat.ts, tests/e2e/adapters/bedrock/chat.test.ts
Ref: #176
TODOs:
- verify whether the response corresponds to `EmbeddingOutput` schema
cc @abughali
=> feat(adapters): add embedding support for Bedrock

examples/agents/granite/granite_wiki_bee.ts, examples/tools/custom/piping.ts, src/internals/helpers/promise.ts, src/internals/types.ts, src/tools/search/wikipedia.ts
Ref: https://github.com/i-am-bee/bee-api/pull/143
=> fix(tools): add proper wikipedia result types

docs/tools.md, examples/tools/mcp.ts
Signed-off-by: Tomas Pilar <tomas.pilar@apoco.com>
Closes: #
=> chore(tools): additional documentation for MCPTool usage

src/agents/bee/prompts.ts
Now I'm not sure if it has any effect.
=> fix(prompt): uncouple analyze and summarize

.husky/pre-commit, package.json
=> docs: properly handle links check

.env.template, docs/searxng-tool.md, docs/tools.md, src/adapters/openai/chat.ts, src/tools/search/searXNGSearch.ts
Introduces a searXNG web search tool. This provides a convenient option for locally deployed agents that require access to web search. No API key is required and the quality of the results are good.
https://github.com/searxng/searxng
Typical use case is that you spin up a searxng local docker container which provides an api endpoint. Agent can then make web searches using this tool to access the searxng api.
I didn't provide an associated test case because it would require a running searxng instance.
=> feat(tools): searXNG web search tool

README.md, docs/README.md
Updates the bee main banner image.
=> docs: update bee profile image

README.md, docs/README.md
=> docs: update readme

docs/integrations.md, docs/migration_guide.md, docs/workflows.md, examples/integrations/langgraph.ts, examples/workflows/agent.ts, examples/workflows/competitive-analysis/workflow.ts, examples/workflows/contentCreator.ts, examples/workflows/multiAgents.ts, examples/workflows/multiAgentsSimple.ts, examples/workflows/nesting.ts, examples/workflows/simple.ts, src/serializer/utils.ts, src/workflows/agent.ts, src/workflows/workflow.ts
=> feat(workflows): update interface

python/README.md, python/docs/README.md
=> docs: update python/README.md

README.md, docs/_sidebar.md, docs/index.html, python/README.md, python/docs/_sidebar.md, typescript/README.md, typescript/docs/_sidebar.md
Closes: #
This PR updates the 3 core README files. I fixed broken links and incorporated Maya's feedback.
=> docs: updated READMEs

python/CONTRIBUTING.md
Closes: #
updated the **[Clone and set up the code](https://github.com/i-am-bee/beeai-framework/blob/main/python/CONTRIBUTING.md#clone-and-set-up-the-code)** section in the contributing guidelines to include the step to go into the `python` directory (before running `poetry install`)
=> docs: update set up instructions

README.md
revision for concision and clarity
NA
Does not address issue, this is an edit of the readme for concision and clarity. reordered the Why BeeAI items, unified structure of each bullet, and tightened language to improve readability.
=> docs: readability pass for readme

python/docs/backend.md, python/docs/emitter.md, python/docs/index.html, python/docs/instrumentation.md, python/docs/tools.md
=> docs: remove old refs after repo migration

README.md, python/README.md, typescript/README.md
=> docs: content update and fix broken links

python/examples/notebooks/README.md, python/examples/notebooks/basics.ipynb
Closes: n/a
Minor updates to notebooks
- typos (very minor)
- add info on installing granite into readme - previously the link was to ollama site, and only covered ollama not the model
- add info on non-mac platforms for ollama/granite - the ibm link is mac only. Couldn't see other platforms?
Note:
1. the earlier change to strip output is now not done. 
2. the notebook has been re-run and so actual llm results will vary
Will add additional files as testing.
=> docs(agents): Minor updates to notebooks (typo/instructions)

python/beeai_framework/agents/bee/agent.py, python/beeai_framework/agents/runners/default/runner.py, python/beeai_framework/agents/runners/granite/prompts.py, python/beeai_framework/agents/runners/granite/runner.py, python/beeai_framework/agents/types.py, python/beeai_framework/backend/chat.py, python/beeai_framework/backend/message.py, python/beeai_framework/backend/utils.py, python/beeai_framework/parsers/field.py, python/beeai_framework/parsers/line_prefix.py, python/beeai_framework/utils/strings.py, python/beeai_framework/utils/templates.py, python/examples/backend/providers/ollama.py, python/examples/runners/basic_runner.py, python/poetry.lock, python/pyproject.toml, python/tests/parsers/line_prefix_test.py
=> feat(parsers): add line prefix parser

python/CONTRIBUTING.md
Small doc update to use an underscore and correct version for installing the new built package
=> docs: fix instructions to install built package

README.md, python/README.md, typescript/README.md, typescript/package.json
1. typescript README: simplified header, added tags, removed "why beeai" section for simplicity. added cross-link to python library. this section will remain in the beeai-framework top level readme
2. python README: updated header to include tags and cross-link to typescript library. removed "why beeai" section, which will remain in the top level framework readme.
3. main README: simplified header and added shields. merged rockets on latest updates to single rocket in header of update section. 
Closes: # NA
=> docs: update 3 main README files

python/beeai_framework/agents/base.py, python/beeai_framework/backend/chat.py
- fix types
- error propagating
Ref: #378
=> feat: typings and error propagating

README.md, python/README.md, python/docs/agents.md, python/docs/memory.md, python/docs/workflows.md, python/examples/agents/custom_agent.py, python/examples/memory/custom.py, python/examples/workflows/nesting.py
Docs updates:
- python agents.md --> Content improvements update + added simple agent code snippet
- main README --> added source for quick example
- python README --> added source for quick example, extended modules section content and renamed to "features"
- python workflows.md --> Content improvements update + added relevant code snippets
- python memory.md --> Content improvements update + added relevant code snippets
Added placeholders for examples needed:
- python/examples/memory/custom.py
- python/examples/workflows/nesting.py
- python/examples/agents/custom_agent.py
Closes: #
=> docs: updates

python/tests/backend/test_chatmodel.py, python/tests/backend/test_message.py, python/tests/errors_test.py, python/tests/parsers/line_prefix_test.py, python/tests/runners/test_default_runner.py, python/tests/templates/test_templates.py, python/tests/test_retryable.py, python/tests/tools/test_duckduckgo.py, python/tests/tools/test_mcp_tool.py, python/tests/tools/test_opemmeteo.py, python/tests/tools/test_wikipedia.py, python/tests/utils/test_custom_logger.py, python/tests/workflows/test_multi_agents.py, python/tests/workflows/test_workflow.py
Closes: #400
Resolves the problem described in #400.  I've also refactored `python/tests/errors_test.py` to make it consistent with the way all the other tests have been written.  
Note: all of the unit tests are passing for me.  There are now considerably more of them running.  However, there are some failures on e2e tests that we should investigate and fix as part of a follow-up task.
=> fix: tests not running due to not being properly decorated

python/docs/serialization.md
=> docs: updates round 2

python/README.md, python/docs/agents.md, python/docs/backend.md, python/docs/cache.md, python/docs/instrumentation.md, python/docs/tutorials.md, python/docs/version.md, python/docs/workflows.md
updates to 
- python README
- agent docs
- backend
- cache
- instrumentation
- tutorials
- version
- workflows
Closes: #
=> docs(several): updates round 3

python/beeai_framework/errors.py, python/tests/errors_test.py
Closes: n/a
Fixes error class:
- Default retryable was false -> corrected to true (as in typescript)
- Default fatal was true -> corrected to false (as in typescript)
- removed unused errors (as mentioned in previous reviews)
- made is_fatal (currently unused) a static method  to match is_retryable (already used) , and fixed issue - needed to ensure it was a FrameworkError instance
- updated unit tests
- checked pytests run clean
=> fix: corrections in error class

python/docs/agents.md, python/docs/cache.md, python/docs/instrumentation.md, python/docs/integrations.md, python/docs/memory.md, python/docs/searxng-tool.md, python/docs/serialization.md, python/docs/sql-tool.md, python/docs/version.md
=> docs(several): updates round 4

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/agents/base.py, python/beeai_framework/agents/runners/base.py, python/beeai_framework/agents/runners/default/runner.py, python/beeai_framework/agents/types.py, python/beeai_framework/backend/chat.py, python/beeai_framework/cancellation.py, python/beeai_framework/context.py, python/beeai_framework/errors.py, python/beeai_framework/retryable.py, python/beeai_framework/utils/counter.py, python/beeai_framework/utils/custom_logger.py, python/beeai_framework/utils/models.py, python/examples/agents/bee.py, python/examples/agents/granite.py, python/examples/agents/simple.py, python/poetry.lock, python/pyproject.toml, python/tests/backend/test_chatmodel.py, python/tests/errors_test.py, python/tests/test_retryable.py, python/tests/workflows/test_multi_agents.py
- improve error handling
- unified used exceptions
- fix async cancellation issues (we were using `thread.Timer` which blocked the future rejection)
- remove dead code
- fix retryable class which did not handle exceptions properly, simplify the implementation
- improve type hints
Updated behaviour of `FrameworkError.explain()` method
```
AgentError(beeai_framework.agents.errors): Maximal amount of global retries (0) has been reached.
ChatModelError(beeai_framework.backend.errors): Something went wrong!
ConnectError(httpx): All connection attempts failed
```
Fixes: #378
=> feat: improve error handling

python/docs/memory.md, python/examples/memory/base.py, python/examples/memory/custom.py, python/examples/memory/llmMemory.py
Covers part of #336 but does not close it entirely.
add python memory examples and docs
=> docs(memory): add python memory examples and docs

python/docs/tools.md, python/examples/tools/advanced.py, python/examples/tools/agent.py, python/examples/tools/base.py, python/examples/tools/custom/base.py, python/examples/tools/custom/openlibrary.py
Contributes-to: https://github.com/i-am-bee/internal/issues/104
update tool docs and add missing examples
=> docs(tools): update tool docs and add missing examples

README.md, python/examples/notebooks/README.md
Closes: n/a
- README.md
- contribution guidelines pointed to typescript version. We have two different sets of docs for python and typescript. As an immediate fix, Added unique links to both. Longer term We could consider a common file at top level, and move common topics there before pointing to python/typescript specifics
- Samples directory was also the typescript version. Followed same approach as above - two links
- Link to multiagent ts example was pointing to readme. corrected to point to most similar ts example (weather workflow)
- python/examples/notebooks
- fixed coalesced bullet points for installing ollama + model (and expanded text to look more consistent)
Alternatively the lists could be collapsed to a simple statement.
=> docs: Corrections in top-level & python notebook readmes

python/beeai_framework/agents/base.py, python/beeai_framework/backend/chat.py, python/beeai_framework/memory/summarize_memory.py, python/docs/agents.md, python/docs/memory.md, python/examples/agents/bee.py, python/examples/agents/granite.py, python/examples/memory/agentMemory.py
Addresses review comments from #397 that were missed due to auto-merge
=> fix: missed review from #397

python/beeai_framework/tools/search/duckduckgo.py, python/beeai_framework/tools/search/wikipedia.py, python/beeai_framework/tools/tool.py, python/beeai_framework/tools/weather/openmeteo.py, python/docs/tools.md, python/examples/tools/custom/base.py, python/examples/tools/custom/openlibrary.py
Related:
- https://github.com/i-am-bee/beeai-framework/pull/429
- https://github.com/i-am-bee/beeai-framework/issues/398
this PR is a follow-up to a [review comment in #429](https://github.com/i-am-bee/beeai-framework/pull/429#pullrequestreview-2651164388). it also unblocks #398 
it makes the `Tool._run` method async and updates the code and doc references accordingly
=> fix: async _run

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/backend/chat.py
`
follow-up to #457 
update parameters
=> fix: chatmodel params None

python/beeai_framework/adapters/litellm/chat.py, python/tests/backend/test_chatmodel.py
related https://github.com/i-am-bee/beeai-framework/pull/457
this PR is a follow up to https://github.com/i-am-bee/beeai-framework/pull/457 and updates the `parameters.model_dump()` to exclude parameters which are not set. otherwise it can cause failures with services that do not support some of the parameters
=> fix: disregard unset params

python/.env.example, python/beeai_framework/adapters/groq/__init__.py, python/beeai_framework/adapters/groq/backend/__init__.py, python/beeai_framework/adapters/groq/backend/chat.py, python/beeai_framework/backend/constants.py, python/docs/backend.md, python/examples/backend/providers/groq.py, python/examples/backend/providers/groq_example.py, python/tests/backend/test_chatmodel.py, python/tests/examples/test_examples.py
Closes: #449
Adds support for [Groq](https://groq.com/) backend
- test added to backend tests
- example included
- doc updated 
- default model: llama-3.1-8b-instant ([full list](https://console.groq.com/docs/models))
Still todo/evaluate
=> feat(adapters): Add Groq backend support

python/beeai_framework/agents/bee/agent.py, python/beeai_framework/agents/runners/default/prompts.py, python/beeai_framework/agents/runners/default/runner.py, python/beeai_framework/agents/runners/granite/prompts.py, python/beeai_framework/backend/message.py, python/beeai_framework/template.py, python/tests/templates/test_templates.py, python/tests/workflows/test_multi_agents.py
Add missing handling for
- user prompt input formatting
- handling empty input
=> feat(agents): handle message formatting

python/beeai_framework/agents/types.py, python/beeai_framework/template.py, python/docs/agents.md, python/examples/agents/bee_advanced.py, python/examples/agents/custom_agent.py
Ref #336
Add `custom_agent.py` and `bee_advanced.py` to the examples and update the docs
Also includes some minor fixes
=> feat(examples): Add custom_agent and bee_advanced examples

python/docs/agents.md, python/examples/agents/bee_advanced.py, python/examples/agents/custom_agent.py
Followup to #462 #440 #431
After merging #440 #431 I forgot to update #462 to address the updates made in those PRs. This addresses those changes
=> fix(examples): update new examples to match latest updates to main

python/beeai_framework/adapters/litellm/chat.py
=> fix(backend): correctly merge inference parameters

python/docs/errors.md
Closes: n/a
Adds initial documentation for errors
=> docs: Update documentation for errors (python)

python/docs/errors.md, python/examples/errors/base.py, python/examples/errors/cast.py, python/examples/errors/tool.py
Ref: #336
Updates Python examples to bring to TypeScript parity.  Updates docs.
=> feat(examples): adds error examples and updates error docs

python/beeai_framework/adapters/langchain/__init__.py, python/beeai_framework/adapters/langchain/tools.py, python/beeai_framework/tools/mcp_tools.py, python/beeai_framework/tools/search/duckduckgo.py, python/beeai_framework/tools/search/wikipedia.py, python/beeai_framework/tools/tool.py, python/beeai_framework/tools/weather/openmeteo.py, python/docs/tools.md, python/examples/notebooks/agents.ipynb, python/examples/tools/custom/base.py, python/examples/tools/custom/openlibrary.py, python/examples/tools/langchain.py, python/poetry.lock, python/pyproject.toml, python/tests/tools/test_mcp_tool.py
Closes: #329 
this PR
- implements a framework native tool which wraps a LangChain tool allowing LangChain tools to be used in the framework
- updates tool's `_run` method to include `RunContext` as an argument (to more closely align with TS)
- updates Tools docs page accordingly
- adds multiple `LangChainTool` examples
=> feat: langchain tool

README.md
Correcting the link to python contribution md, It was giving 404 because of wrong link.
Closes: #
=> Update README.md - correcting python contribution guidelines link

python/beeai_framework/backend/chat.py, python/beeai_framework/backend/message.py, python/beeai_framework/tools/tool.py, python/docs/backend.md, python/examples/backend/chat.py, python/examples/backend/chat_stream.py, python/examples/backend/structured.py, python/examples/backend/tool_calling.py
Ref #336 
Adds the basic backend examples and updates the docs. Also includes some Mypy fixes found during my work.
=> test(examples): Add missing backend examples

python/beeai_framework/tools/__init__.py, python/beeai_framework/tools/mcp_tools.py, python/beeai_framework/tools/tool.py, python/beeai_framework/utils/models.py, python/examples/tools/mcp_agent.py, python/examples/tools/mcp_tool_creation.py, python/tests/tools/test_mcp_tool.py
#398 
This PR adds MCPTool and 2 examples.
=> feat(tools): add MCP tool

python/.env.example, python/beeai_framework/adapters/vertexai/__init__.py, python/beeai_framework/adapters/vertexai/backend/__init__.py, python/beeai_framework/adapters/vertexai/backend/chat.py, python/beeai_framework/backend/constants.py, python/docs/backend.md, python/examples/backend/providers/vertexai.py, python/tests/backend/test_chatmodel.py, python/tests/examples/test_examples.py
Closes: #468
Adds Google VertexAI support
Todos
=> feat(adapters): Add Google VertexAI support

python/beeai_framework/tools/mcp_tools.py, python/beeai_framework/utils/models.py, python/examples/tools/mcp_agent.py, python/examples/tools/mcp_tool_creation.py, python/tests/tools/test_mcp_tool.py
Creates more robust Pydantic model based on provided JSON Schema
Ref: #398
=> feat(internals): construct Pydantic model from JSON Schema

python/beeai_framework/utils/custom_logger.py, python/docs/logger.md, python/examples/logger/agent.py, python/examples/logger/base.py
Ref: #336 
Adds logger examples and updates docs
=> feat(examples): adds logger examples and updates docs

python/.env.example, python/beeai_framework/adapters/anthropic/__init__.py, python/beeai_framework/adapters/anthropic/backend/__init__.py, python/beeai_framework/adapters/anthropic/backend/chat.py, python/beeai_framework/backend/constants.py, python/docs/backend.md, python/examples/backend/providers/anthropic.py, python/examples/notebooks/workflows.ipynb, python/tests/backend/test_chatmodel.py, python/tests/examples/test_examples.py
Closes: #521 
Adds support for Anthropic
Default model/tested: claude-3-haiku-20240307
=> feat(adapters): Add Anthropic support

python/beeai_framework/adapters/litellm/_patch.py, python/beeai_framework/adapters/litellm/chat.py
=> fix(backend): handle event loop closed error

python/docs/agents.md, python/docs/cache.md, python/docs/emitter.md, python/docs/errors.md, python/docs/logger.md, python/docs/memory.md, python/docs/serialization.md, python/docs/templates.md, python/docs/tools.md, python/docs/workflows.md
Closes: #493 
Follows precedent from Typescript to embed important examples, and additionally point to the corresponding example folder instead of individual files.
=> docs(examples): unifies example doc links to point to example dirs

python/README.md, python/docs/errors.md, python/docs/events.md, typescript/docs/agents.md, typescript/docs/backend.md, typescript/docs/cache.md, typescript/docs/emitter.md, typescript/docs/errors.md, typescript/docs/integrations.md, typescript/docs/logger.md, typescript/docs/memory.md, typescript/docs/migration_guide.md, typescript/docs/sql-tool.md, typescript/docs/templates.md, typescript/docs/tools.md, typescript/docs/version.md, typescript/docs/workflows.md
docs udpates
- python improvements to errors and events docs and minor update to README
- typescript resolved broken links
Closes: #
=> docs(several): py errors events and ts links fix

.github/PULL_REQUEST_TEMPLATE.md
=> docs(PRtemplate): update pull request template

.github/workflows/docs.yml
Closes: #
Added a link checker
- Now runs on every PR -- but only publishes if a push (ie after a merge)
- Uses the 'lychee' checker (apache 2.0/MIT)
- Creates a job summary 
- Links to '/examples/component/agent.py' or similar will fail. They work on github.io, but also fail locally. Instead use '/python/examples/component/agent.py' which passes link checker, works on github.io, and also resolves locally when browsing source code.
- Latest run: https://github.com/i-am-bee/beeai-framework/actions/runs/13763101279?pr=542
- Current issues logged in https://github.com/i-am-bee/beeai-framework/issues/543
=> docs: Add link checker

.github/workflows/docs.yml
Corrects detection and reporting of anchors
Note: This was fixed by removing the `--base`` option. One side-effect is that errors are now reported relative to the root of the base runner.
This seems the best solution, as manual checking of about half the reports shows that:
- we're now picking up additional bad anchor usage which was previously undetected.
- previous false-positives in the README are now no longer reported
Closes: #557
=> docs: Update link checker for anchor validation

typescript/package.json
Add `commonjs` build compatibility.
You can build it as a commonjs module via `"module": "commonjs"` setting In the tsconfig.json file.
=> fix: typesVersions setting in package.json

README.md, python/CONTRIBUTING.md, python/docs/backend.md, python/docs/serialization.md, python/docs/templates.md, python/examples/README.md, typescript/CONTRIBUTING.md, typescript/README.md
Closes: n/a
- Fixes remaining link errors in docs
- Skipped checks are for some mailto links in a library used in a typescript app
=> docs: Update broken anchor refs

.github/workflows/docs.yml
Closes: n/a
Updates link checker (in docs build action) to fail if any bad links found
This can be combined with a branch protection rule to block PRs that break doclinks
=> chore: Link checker to fail if bad links found

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/agents/tool_calling/__init__.py, python/beeai_framework/agents/tool_calling/agent.py, python/beeai_framework/agents/tool_calling/events.py, python/beeai_framework/agents/tool_calling/prompts.py, python/beeai_framework/agents/tool_calling/types.py, python/beeai_framework/backend/message.py, python/beeai_framework/backend/types.py, python/examples/agents/tool_calling.py
```
python examples/agents/tool_calling.py
```
Ref: #531
=> feat(agents): add tool calling agent

python/examples/README.md
Trivial fix up to the examples README
No code changed
No code changed
=> docs: fix typo

python/examples/observability/simple_observe.py, python/examples/observability/simple_on.py
Closes: #548 
adds on and observe examples for llm create
=> docs(examples): adds on and observe examples for llm create

python/README.md, python/beeai_framework/agents/tool_calling/agent.py, python/beeai_framework/agents/tool_calling/prompts.py, python/beeai_framework/agents/tool_calling/types.py, python/beeai_framework/tools/weather/openmeteo.py, python/beeai_framework/utils/lists.py, python/beeai_framework/workflows/agent.py, python/beeai_framework/workflows/events.py, python/beeai_framework/workflows/workflow.py, python/docs/agents.md, python/docs/workflows.md, python/examples/workflows/multi_agents.py, python/examples/workflows/multi_agents_simple.py, python/examples/workflows/travel_advisor.py, python/tests/workflows/test_multi_agents.py
>Based on #531 
Add structured input to the tool calling agent. provides a way for a developer to provide greater structure to the task that the agent will perform. Includes:
- prompt: could also be named task, what the agent needs to do
- context: in a workflow we would set this to the output of the previous agent(s)
- expected_output: allows the user to define output criteria
All of this is ultimately rendered into the user message, and just provides a structure to help the user to organize the task. 
I proposed we include similar structure when defining the agent i.e. role, background, guidelines etc. Need to figure out a terminology.
=> feat: structured agent input

README.md
Which issue(s) does this pull-request address?
Trivial fix up to the python example README, whose model is not matching the example instructions as instructed below on README
```
To run this example, be sure that you have installed [ollama](https://ollama.com) with the [granite3.1-dense:8b](https://ollama.com/library/granite3.1-dense) model downloaded.
```
General
No code changed
No code changed
Documentation is updated
=> docs: update/fix example model reference to match instructions

python/beeai_framework/utils/models.py
=> fix: handle compositional schemas in JSONSchemaModel

python/beeai_framework/agents/tool_calling/agent.py
=> fix(agents): retry if tool does not exist in ToolCallingAgent

typescript/src/index.ts
I need to export all modules that I want to instrument. The instrumentation package works only with the main module see:
```
import { BeeAIInstrumentation } from "@arizeai/openinference-instrumentation-beeai";
import * as beeaiFramework from "beeai-framework";
const beeAIInstrumentation = new BeeAIInstrumentation();
beeAIInstrumentation.manuallyInstrument(beeaiFramework);
```
=> feat(instrumentation): export modules for instrumentation

python/beeai_framework/agents/react/runners/default/runner.py, python/beeai_framework/emitter/emitter.py, python/beeai_framework/errors.py, python/beeai_framework/tools/errors.py
=> fix(emitter): propagate errors from user callbacks

python/beeai_framework/errors.py, python/beeai_framework/tools/weather/openmeteo.py, python/docs/tools.md, python/examples/tools/advanced.py, python/examples/tools/base.py, python/tests/tools/test_opemmeteo.py
=> feat(tools): improve OpenMeteo input schema

python/beeai_framework/agents/tool_calling/agent.py, python/beeai_framework/agents/tool_calling/prompts.py
=> feat(agents): improve ToolCallingAgent

python/beeai_framework/__init__.py, python/beeai_framework/template.py
=> chore: remove unused code

python/beeai_framework/backend/chat.py, python/beeai_framework/backend/types.py
=> feat(backend): simplify chat model configuration

typescript/docs/workflows.md, typescript/examples/workflows/multiAgents.ts, typescript/src/agents/toolCalling/prompts.ts, typescript/src/workflows/agent.ts
Closes: https://github.com/i-am-bee/beeai-framework/issues/584
=> feat(workflows): refactor multiAgent workflow

python/docs/backend.md, python/examples/backend/chat.py
Closes: #622 
Updates backend chat example to show llm param editing.
=> docs(examples): updates backend chat example to show llm param editing

docs/index.html, python/docs/index.html
=> docs: enable Python code highlighting

typescript/docs/templates.md
**Fix broken link**  
Closes: *N/A (minor fix - no issue created)*  
This PR fixes a broken link in the documentation. No other changes were made.
=> docs: fix broken link in templates.md

python/beeai_framework/adapters/litellm/chat.py
=> fix(backend): handle empty tool calls for vLLM

python/examples/helpers/io.py
Closes: #626
This update the ConsoleReader to gracefully close when encountering an EOF or KeyboardInterrupt rather than throwing an ugly error.
=> test(examples): Update ConsoleReader to handle EOF and SIGINT

python/docs/_sidebar.md, python/docs/agents.md, python/docs/backend.md, python/docs/emitter.md, python/docs/workflows.md
Due to not having any direct links, the events doc was not easily reachable
=> docs(emitter): add links to events doc

python/examples/workflows/travel_advisor.py
Closes: #
Added DuckDuckGoTool to Activity Finder agent & light cleanup in prep for demoing this code in a tutorial video
=> docs(examples): update travel_advisor

python/docs/workflows.md
=> docs(workflows): remove experimental tag

typescript/examples/agents/react.ts
Ref: https://github.com/i-am-bee/beeai-framework-starter/pull/23
There was a typo in the env var in beeai-framework-starter, after https://github.com/i-am-bee/beeai-framework-starter/pull/23 fixes that typos we need to update our usage (the only usage of that var in i-am-bee repos)
=> test: fix code interpreter env var typo

python/beeai_framework/agents/react/agent.py, python/beeai_framework/agents/react/runners/default/runner.py, python/beeai_framework/agents/react/types.py
=> fix(agents): respect the stream parameter in the ReActAgent

python/docs/tutorials.md, python/examples/tools/mcp_slack_agent.py, python/tests/examples/test_examples.py
Closes: #677 
This PR improves the clarity and consistency of the tutorials documentation as we continue adding more tutorials. It also includes an MCP example in our examples library and uses EmbedMe to reference it within the tutorial.
=> docs(tutorials): Enhance tutorials.md

python/docs/tools.md
=> docs(tools): add PythonTool SandboxTool to tools.md

README.md
Closes: #
Added a tip to the main python README: Get started quickly with the [beeai-framework-py-starter](https://github.com/i-am-bee/beeai-framework-py-starter) template.
=> docs(README): Update README.md to reference starter

python/examples/helpers/io.py
=> chore: print the stdin content when using redirection

python/poetry.lock, python/pyproject.toml
=> test: run tests in parallel

MAINTAINERS.md
=> docs(maintainers): Create MAINTAINERS.md

python/tests/tools/test_sandbox.py
=> test: fix decorator typo

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/backend/message.py
=> feat(backend): disable loading of external cost map in LiteLLM by default

python/beeai_framework/agents/tool_calling/agent.py, python/beeai_framework/agents/tool_calling/prompts.py, python/beeai_framework/tools/search/base.py, python/beeai_framework/tools/search/wikipedia.py, python/beeai_framework/tools/tool.py, python/beeai_framework/utils/strings.py, python/beeai_framework/workflows/agent/agent.py, python/docs/agents.md, python/docs/workflows.md, python/examples/agents/tool_calling.py, python/examples/workflows/multi_agents.py, python/examples/workflows/multi_agents_simple.py
Ref: #624
- enforce tool usage in ToolCallingAgent
- extend tool's decorator to allow overrides
=> feat(agents): enforce tool usage in ToolCallingAgent

python/beeai_framework/agents/tool_calling/agent.py
=> fix(agents): avoid message duplication in ToolCallingAgent

.github/workflows/py_e2e_tests.yml
=> ci: update python e2e trigger

typescript/package.json, typescript/yarn.lock
=> chore: bump acp version

docs-mintlify/docs.json
Related-to: #675 
Updates social media links in page footer
- removed mintlify links
- Added youtube/bluesky/github/discord
Note, I did not update the sidebar which currently has discord/github only.
Do we want the full set there? Or none?
=> docs: fix footers with social  media links

python/beeai_framework/adapters/watsonx/backend/chat.py
=> fix(adapters): update tool_choice list in Watsonx

python/examples/workflows/travel_advisor.py
=> chore: update travel advisor example

python/beeai_framework/context.py
=> fix: context var storage cleanup

python/docs/tutorials.md, python/examples/tools/mcp_slack_agent.py
=> chore(mcp): fix MCP example to prevent ClosedResourceError

python/beeai_framework/agents/experimental/remote/agent.py, python/poetry.lock, python/pyproject.toml
=> chore: make ACP SDK an optional dependency

python/beeai_framework/context.py
=> feat: allow consuming Run instance as an async generator

python/poetry.lock, python/pyproject.toml
=> chore(deps): upgrade DuckDuckGo search

typescript/src/adapters/anthropic/backend/client.ts, typescript/src/adapters/azure-openai/backend/client.ts, typescript/src/adapters/groq/backend/client.ts, typescript/src/adapters/watsonx/backend/client.ts, typescript/src/backend/client.ts
Ref: #780 (affects other providers as well)
=> fix(backend): correctly propagate settings to LLM backends

python/beeai_framework/tools/types.py, python/docs/tools.md, python/examples/agents/experimental/human.py, python/examples/tools/custom/openlibrary.py, python/examples/tools/experimental/human.py
=> feat(tools): improve type hints for JSONToolOutput

python/CONTRIBUTING.md
=> docs: update CONTRIBUTING.md

python/beeai_framework/adapters/amazon_bedrock/backend/chat.py, python/beeai_framework/adapters/anthropic/backend/chat.py, python/beeai_framework/adapters/azure_openai/backend/chat.py, python/beeai_framework/adapters/groq/backend/chat.py, python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/adapters/ollama/backend/chat.py, python/beeai_framework/adapters/openai/backend/chat.py, python/beeai_framework/adapters/vertexai/backend/chat.py, python/beeai_framework/adapters/watsonx/backend/chat.py, python/beeai_framework/adapters/xai/backend/chat.py, python/beeai_framework/backend/chat.py, python/beeai_framework/utils/dicts.py, python/docs/backend.md, python/examples/backend/providers/watsonx.py, python/tests/backend/providers/test_azure_openai.py, python/tests/backend/test_chatmodel.py
Closes: #
The following PR handles issues with ENVs for Chat Models. Sometimes errors were thrown from LiteLLM sometimes they were thrown from the framework. Some ENVs were propagated from the constructor, some were not. Generally, there was no type interference for API Keys etc. This PR addresses that.
=> feat(backend): improve type hints and env loading

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/adapters/ollama/backend/chat.py, python/beeai_framework/backend/chat.py, python/beeai_framework/backend/utils.py, python/poetry.lock
Ref: #788
- allow changing the strictness of generated schemas for tools and response formats
- fix incorrect position of the `strict` property in generated JSON Schemas
=> feat(backend): add the ability to change the strictness of a tool input and response format schema

typescript/examples/internals/fetcher.ts, typescript/src/internals/fetcher.ts, typescript/tests/examples/examples.test.ts
=> feat(internals): update RestfulClient capabilities

typescript/examples/agents/experimental/remote.ts, typescript/package.json, typescript/src/agents/experimental/remote/agent.ts, typescript/src/internals/fetcher.ts, typescript/yarn.lock
=> feat(agents): rewrite remote agent to ACP

python/beeai_framework/agents/experimental/remote/__init__.py, python/beeai_framework/agents/experimental/remote/agent.py, python/beeai_framework/agents/experimental/remote/events.py, python/beeai_framework/agents/experimental/remote/types.py, python/docs/agents.md, python/docs/tutorials.md, python/examples/agents/experimental/remote.py, python/examples/workflows/remote.py, python/poetry.lock, python/pyproject.toml
=> feat(agent): use new ACP-SDK in remote agent

python/beeai_framework/backend/types.py
=> fix(backend): update types for chat model parameters

python/beeai_framework/backend/utils.py, python/beeai_framework/tools/openapi.py
=> feat(tools): improve schema parsing in OpenAPITool

python/beeai_framework/adapters/watsonx/backend/chat.py, python/beeai_framework/backend/chat.py, python/beeai_framework/backend/message.py, python/beeai_framework/utils/models.py
=> feat(backend): detect invalid tool calls due to the max token constraint

typescript/examples/backend/providers/watsonx.ts, typescript/package.json, typescript/src/adapters/amazon-bedrock/backend/client.ts, typescript/src/adapters/anthropic/backend/client.ts, typescript/src/adapters/azure-openai/backend/client.ts, typescript/src/adapters/google-vertex/backend/client.ts, typescript/src/adapters/groq/backend/client.ts, typescript/src/adapters/ollama/backend/client.ts, typescript/src/adapters/openai/backend/client.ts, typescript/src/adapters/vercel/backend/chat.ts, typescript/src/adapters/vercel/backend/utils.ts, typescript/yarn.lock
Ref: #821
- add a workaround to "inject" messages with a custom role to bypass Vercel AI SDK validation
=> fix(backend): handle inference calls for custom messages

python/beeai_framework/agents/tool_calling/agent.py, python/beeai_framework/agents/tool_calling/prompts.py, python/beeai_framework/agents/tool_calling/types.py, python/beeai_framework/agents/tool_calling/utils.py, python/beeai_framework/utils/counter.py, python/beeai_framework/utils/models.py, python/beeai_framework/utils/strings.py, python/beeai_framework/workflows/agent/agent.py
=> feat(agents): prevent cycles in ToolCallingAgent

python/beeai_framework/adapters/acp/__init__.py, python/beeai_framework/adapters/acp/serve/server.py, python/beeai_framework/adapters/mcp/__init__.py, python/beeai_framework/adapters/mcp/serve/__init__.py, python/beeai_framework/adapters/mcp/serve/server.py, python/beeai_framework/serve/server.py, python/beeai_framework/utils/funcs.py, python/examples/README.md, python/examples/serve/acp.py, python/examples/serve/mcp_tool.py, python/tests/examples/test_examples.py
Add support for MCP and expose all Tools
=> feat(adapters): add MCP server adapter

python/beeai_framework/adapters/acp/serve/agent.py, python/beeai_framework/adapters/acp/serve/server.py, python/beeai_framework/adapters/beeai_platform/agents/agent.py, python/poetry.lock, python/pyproject.toml
=> feat(adapters): add validation checks for ACP and BeeAI Platform

python/docs/_sidebar.md, python/docs/serve.md
=> docs: serve module

python/docs/integrations.md
=> docs(mcp): update MCP integration docs

docs-mintlify/docs.json, docs-mintlify/guides/integrations.mdx, docs-mintlify/modules/serve.mdx
=> docs: add serve and integrations docs pages

docs-mintlify/experimental/requirement-agent.mdx
=> docs: update req agent docs

python/beeai_framework/emitter/emitter.py
Closes: #
- correctly awaits coroutines
- cancel running tasks in case of error
- improve error message
=> fix: properly invoke sync and async callbacks in runs

python/beeai_framework/adapters/acp/serve/agent.py, python/beeai_framework/adapters/litellm/embedding.py, python/beeai_framework/adapters/openai/backend/embedding.py, python/beeai_framework/agents/experimental/utils/_llm.py, python/beeai_framework/tools/search/base.py, python/beeai_framework/tools/search/wikipedia/wikipedia.py, python/beeai_framework/utils/io.py
=> fix: set value for aliases in embedding model

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/backend/types.py, python/beeai_framework/utils/dicts.py
=> fix(backend): add missing usage data during streaming

mise.toml, python/beeai_framework/adapters/mcp/serve/server.py
=> fix(adapters): fix MCP server

docs/community/community-calls/15-07-2025.md
=> docs: Create 15-07-2025.md

python/beeai_framework/tools/mcp/mcp.py
=> Fixed mcp tool causing error

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/adapters/ollama/backend/chat.py, python/beeai_framework/adapters/openai/backend/chat.py, python/beeai_framework/adapters/watsonx/backend/chat.py, python/beeai_framework/backend/chat.py
=> feat(backend): update tool choice support for OpenAI Compatible endpoints

docs/modules/backend.mdx, python/beeai_framework/adapters/gemini/__init__.py, python/beeai_framework/adapters/gemini/backend/__init__.py, python/beeai_framework/adapters/gemini/backend/chat.py, python/beeai_framework/adapters/gemini/backend/embedding.py, python/beeai_framework/backend/constants.py, python/examples/backend/providers/gemini.py, python/poetry.lock, python/pyproject.toml, python/tests/examples/test_examples.py
There is no support for [Google Gemini Developer API](https://ai.google.dev/gemini-api/docs).
This PR adds support for [Google Gemini Developer API](https://ai.google.dev/gemini-api/docs) (Python only).
=> feat(adapters): add Gemini (Google Gemini Developer API) backend provider

typescript/src/tools/mcp.ts
=> fix(tools): sanitize names in the MCPTool

docs/docs.json, docs/modules/rag.mdx, python/README.md, python/examples/agents/rag_agent.py, python/examples/backend/module_loading.py, python/tests/examples/test_examples.py
Added RAG (Retrieval-Augmented Generation) documentation covering the framework's approach to building intelligent agents that combine semantic search with language models
=> docs: RAG components and agent documentation

README.md, python/README.md
=> docs: Update READMEs

python/beeai_framework/agents/experimental/agent.py
=> feat(agents): add abort signal to RequirementAgent

docs/integrations/mcp.mdx, python/beeai_framework/adapters/mcp/serve/server.py, python/examples/serve/mcp_tool.py, python/poetry.lock
=> chore: update to a new mcp version

python/beeai_framework/backend/chat.py
=> feat(backend): detect non-supported tool choice values

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/agents/experimental/agent.py, python/beeai_framework/agents/tool_calling/agent.py, python/beeai_framework/backend/chat.py, python/beeai_framework/backend/message.py, python/beeai_framework/backend/types.py, python/examples/agents/experimental/requirement/demo.py, python/examples/backend/providers/ollama.py, python/examples/backend/providers/openai_example.py, python/poetry.lock, python/tests/backend/test_chatmodel.py
=> fix(backend): correctly process streaming chunks

docs/modules/rag.mdx, python/beeai_framework/adapters/beeai/backend/document_processor.py, python/beeai_framework/agents/experimental/rag/agent.py, python/beeai_framework/backend/constants.py, python/beeai_framework/backend/document_processor.py, python/examples/agents/rag_agent.py
Support dynamic loading of document processors
=> feat(backend): Support dynamic loading of document processors

python/beeai_framework/agents/experimental/_utils.py, python/beeai_framework/backend/chat.py
=> fix(agents): exclude hidden tools from the system prompt (RequirementAgent)

python/beeai_framework/tools/mcp/mcp.py, python/beeai_framework/tools/mcp/utils/session_provider.py
=> fix(tools): handle MCP client session cleanup

python/beeai_framework/tools/tool.py, python/beeai_framework/utils/strings.py
=> feat: improve serialization

docs/modules/observability.mdx
=> docs: observability enhancements

python/beeai_framework/adapters/a2a/agents/_utils.py, python/beeai_framework/adapters/a2a/agents/agent.py, python/beeai_framework/adapters/a2a/serve/agent_executor.py, python/beeai_framework/adapters/beeai_platform/serve/server.py
=> feat(adapters): improve a2a client

docs/integrations/beeai-platform.mdx, docs/modules/serve.mdx, python/examples/workflows/remote.py
Closes: https://github.com/i-am-bee/beeai-framework/issues/1033
=> docs: update BeeAI Platform integration

python/beeai_framework/adapters/beeai_platform/serve/server.py, python/poetry.lock, python/pyproject.toml
=> feat(adapters): update agent's trajectory in BeeAI Platform

python/beeai_framework/tools/handoff.py
Ref: #1050
- ignores system messages (might prevent errors)
- allows to optionally pass the tool's input to the agent
- adds documentation
- handles "invalid" inputs (multiple tool calls)
=> feat(tools): improve Handoff tool

python/beeai_framework/adapters/litellm/chat.py, python/beeai_framework/backend/chat.py, python/beeai_framework/backend/types.py, python/beeai_framework/retryable.py
=> feat: add retry logic to ChatModel

docs/integrations/acp.mdx, python/beeai_framework/adapters/a2a/serve/agent_executor.py, python/beeai_framework/adapters/acp/agents/agent.py, python/beeai_framework/adapters/acp/serve/server.py, python/beeai_framework/adapters/beeai_platform/serve/server.py, python/beeai_framework/adapters/mcp/serve/server.py, python/beeai_framework/adapters/watsonx_orchestrate/serve/_factories/_react_agent.py, python/beeai_framework/adapters/watsonx_orchestrate/serve/_factories/_requirement_agent.py, python/beeai_framework/adapters/watsonx_orchestrate/serve/_factories/_tool_calling_agent.py, python/examples/agents/providers/acp.py, python/examples/serve/acp.py, python/poetry.lock, python/pyproject.toml
Closes: https://github.com/i-am-bee/beeai-framework/issues/1058
=> Support paralell agent runs

python/beeai_framework/adapters/beeai_platform/serve/io.py, python/beeai_framework/adapters/beeai_platform/serve/server.py
=> feat(serve): async IO support in BeeAI Platform

python/beeai_framework/tools/mcp/mcp.py, python/tests/tools/test_mcp_tool.py
Closes: https://github.com/i-am-bee/beeai-framework/issues/1064
=> feat(tools): raise error in MCP tool if result has an error

docs/integrations/a2a.mdx, docs/modules/serve.mdx, python/beeai_framework/adapters/a2a/agents/_utils.py, python/beeai_framework/adapters/a2a/agents/agent.py, python/beeai_framework/adapters/a2a/agents/events.py, python/beeai_framework/adapters/a2a/agents/types.py, python/beeai_framework/adapters/a2a/serve/server.py, python/beeai_framework/adapters/beeai_platform/agents/agent.py, python/beeai_framework/adapters/beeai_platform/agents/events.py, python/beeai_framework/adapters/beeai_platform/agents/types.py, python/beeai_framework/adapters/beeai_platform/serve/server.py, python/examples/serve/a2a_server.py, python/poetry.lock, python/pyproject.toml
Ref: https://github.com/i-am-bee/beeai-framework/issues/1053
=> feat(adapters): add support for multiple a2a protocols

python/beeai_framework/adapters/beeai_platform/backend/chat.py, python/beeai_framework/adapters/beeai_platform/context.py, python/beeai_framework/adapters/beeai_platform/serve/io.py, python/beeai_framework/adapters/beeai_platform/serve/server.py, python/beeai_framework/agents/react/agent.py
=> feat(adapters): handle nested initialization of BeeAIPlatformChatModel

python/poetry.lock, python/pyproject.toml
Closes: #751 
Added extra dependencies for vertex and bedrock backend providers.
=> chore(deps): add extra dependencies

python/beeai_framework/adapters/beeai_platform/backend/chat.py
=> fix(adapters): correctly wrap the inner model in BeeAIPlatformChatModel

docs/introduction/tour.mdx
fixed the observability broken link and rewrote the main description 
Closes: #
=> docs: Update tour.mdx

docs/integrations/a2a.mdx, typescript/examples/agents/providers/a2a.ts, typescript/package.json, typescript/src/adapters/a2a/agents/agent.ts, typescript/src/adapters/a2a/agents/events.ts, typescript/src/adapters/a2a/agents/types.ts, typescript/src/adapters/a2a/agents/utils.ts, typescript/src/backend/message.ts, typescript/tests/examples/examples.test.ts, typescript/yarn.lock
Ref: https://github.com/i-am-bee/beeai-framework/issues/1029
=> feat(adapters): add A2AAgent to TS

docs/experimental/requirement-agent.mdx, python/examples/agents/experimental/requirement/quickstart_requirement.py
=> docs: revising the requirement agent page

docs/introduction/tour.mdx, docs/modules/agents.mdx
=> docs: revised the tour de framework and fixed code example issues

docs/integrations/a2a.mdx, docs/modules/serve.mdx, python/CHANGELOG.md, python/beeai_framework/adapters/a2a/agents/agent.py, python/beeai_framework/adapters/a2a/serve/agent_executor.py, python/beeai_framework/adapters/a2a/serve/server.py, python/examples/agents/providers/a2a_agent.py, python/examples/serve/a2a_server.py
=> feat(adapters): update A2AServer and events

docs/modules/backend.mdx, python/examples/backend/providers/openai_example.py
=> docs: backend revision

python/poetry.lock, python/pyproject.toml
=> fix: temporary fix uvicorn version

README.md
n/a
Closes: #
The multiagent example in the README throws an exception when run because of an incorrect attribute path:
`print("Agent:", response.answer.text)`
should be
`print("Agent:", response.state.result.response)`
=> docs: fix multiagent example in readme
